/** BGG category/mechanic labels (EN) → German display names. */
export const BGG_TAXONOMY_DE: Record<string, string> = {
  // Categories
  Adventure: "Abenteuer",
  "Age of Reason": "Zeitalter der Aufklärung",
  "American West": "Wilder Westen",
  Ancient: "Antike",
  Animals: "Tiere",
  "Aviation / Flight": "Luftfahrt",
  Bluffing: "Bluffen",
  "Card Game": "Kartenspiel",
  "City Building": "Städtebau",
  Civilization: "Zivilisation",
  "Collectible Components": "Sammelkomponenten",
  "Comic Book / Strip": "Comic / Comicstrip",
  Deduction: "Deduktion",
  Dice: "Würfel",
  Economic: "Wirtschaft",
  Environmental: "Umwelt",
  "Expansion for Base-game": "Erweiterung zum Basisspiel",
  Exploration: "Erkundung",
  Fantasy: "Fantasy",
  Farming: "Landwirtschaft",
  Fighting: "Kampf",
  Horror: "Horror",
  Humor: "Humor",
  "Industry / Manufacturing": "Industrie / Fertigung",
  Mafia: "Mafia",
  "Mature / Adult": "Ab 18",
  Maze: "Labyrinth",
  Medieval: "Mittelalter",
  Memory: "Gedächtnis",
  "Murder / Mystery": "Krimi / Mystery",
  Music: "Musik",
  Miniatures: "Miniaturen",
  "Modern Warfare": "Moderne Kriegsführung",
  "Movies / TV / Radio theme": "Film, TV & Radio",
  Nautical: "Seefahrt",
  Negotiation: "Verhandlung",
  "Novel-based": "Literaturvorlage",
  "Party Game": "Partyspiel",
  Pirates: "Piraten",
  Political: "Politik",
  "Post-Napoleonic": "Nach-Napoleonisch",
  Racing: "Rennen",
  "Real-time": "Echtzeit",
  Religious: "Religion",
  "Science Fiction": "Science-Fiction",
  "Space Exploration": "Weltraumforschung",
  "Territory Building": "Gebietsaufbau",
  Trains: "Züge",
  Transportation: "Transport",
  Trivia: "Wissensspiel",
  "Video Game Theme": "Videospielthema",
  Wargame: "Kriegsspiel",
  Zombies: "Zombies",

  // Mechanics
  "Action Points": "Aktionspunkte",
  "Action Queue": "Aktionsreihe",
  "Action Retrieval": "Aktion zurückholen",
  "Advantage Token": "Vorteilsmarker",
  Alliances: "Allianzen",
  "Area Majority / Influence": "Gebietsherrschaft / Einfluss",
  "Area Movement": "Gebietbewegung",
  "Area-Impulse": "Gebietsimpuls",
  "Auction / Bidding": "Auktion / Bieten",
  "Auction: Sealed Bid": "Verdeckte Gebote",
  "Auction: Turn Order Until Pass": "Auktion: Zugreihenfolge bis Pass",
  "Automatic Resource Growth": "Automatisches Ressourcenwachstum",
  "Betting and Bluffing": "Wetten und Bluffen",
  Bias: "Startvorteil",
  "Campaign / Battle Card Driven": "Kampagnen- & Schlachtkarten",
  "Card Play Conflict Resolution": "Kartenkampf",
  "Catch the Leader": "Aufholjagd",
  Chaining: "Verkettung",
  "Closed Drafting": "Geschlossenes Drafting",
  "Commodity Speculation": "Warenspekulation",
  "Communication Limits": "Kommunikationsbeschränkung",
  Contracts: "Verträge",
  "Cooperative Game": "Kooperatives Spiel",
  "Critical Hits and Failures": "Kritische Treffer und Fehlschläge",
  "Deck Construction": "Deckbau",
  "Deck, Bag, and Pool Building": "Deck-, Beutel- und Poolbildung",
  "Delayed Purchase": "Verzögerter Kauf",
  "Dice Rolling": "Würfeln",
  "Die Icon Resolution": "Würfelsymbol-Auflösung",
  Enclosure: "Umschließen",
  "End Game Bonuses": "Endspielboni",
  Events: "Ereignisse",
  "Force Commitment": "Truppenbindung",
  "Grid Coverage": "Rasterabdeckung",
  "Grid Movement": "Rasterbewegung",
  "Hand Management": "Handmanagement",
  "Hexagon Grid": "Sechseckraster",
  "Hidden Movement": "Verdeckte Bewegung",
  "Hidden Roles": "Verdeckte Rollen",
  "Hidden Victory Points": "Verdeckte Siegpunkte",
  "Hot Potato": "Heiße Kartoffel",
  Income: "Einkommen",
  "Increase Value of Unchosen Resources": "Wert ungenutzter Ressourcen",
  Interrupts: "Unterbrechungen",
  "Kill Steal": "Kill Steal",
  "King of the Hill": "König des Hügels",
  "Legacy Game": "Legacy-Spiel",
  "Line Drawing": "Linienzeichnen",
  "Line of Sight": "Sichtlinie",
  Loans: "Darlehen",
  "Lose a Turn": "Zug verlieren",
  "Map Addition": "Kartenerweiterung",
  "Map Deformation": "Kartenverformung",
  "Map Reduction": "Kartenverkleinerung",
  Market: "Markt",
  "Melding and Splaying": "Melden und Auslegen",
  "Modular Board": "Modulares Spielbrett",
  "Movement Points": "Bewegungspunkte",
  "Multi-Use Cards": "Mehrfachnutzbare Karten",
  "Multiple Maps": "Mehrere Karten",
  "Narrative Choice / Paragraph": "Absatz-System",
  "Neighbor Scope": "Nachbarbereich",
  "Network and Route Building": "Netzwerk- und Routenbau",
  "Once-Per-Game Abilities": "Einmal-pro-Spiel-Fähigkeiten",
  "Open Drafting": "Offenes Drafting",
  "Order Counters": "Reihenfolgezähler",
  Ordering: "Reihenfolge",
  Ownership: "Besitz",
  "Passed Action Token": "Weitergereichter Aktionsmarker",
  "Pattern Building": "Musterlegen",
  "Pattern Movement": "Mustergesteuerte Bewegung",
  "Pick-up and Deliver": "Abholen und Liefern",
  "Player Elimination": "Spielerausschluss",
  "Programmed Movement": "Programmierte Bewegung",
  "Push Your Luck": "Push-your-Luck",
  Race: "Wettlauf",
  "Random Production": "Zufällige Produktion",
  "Re-rolling and Locking": "Neu-Würfeln und Festhalten",
  "Real-Time": "Echtzeit",
  "Relative Movement": "Relative Bewegung",
  "Role Playing": "Rollenspiel",
  "Scenario / Mission / Campaign Game":
    "Szenario-, Missions- & Kampagnenspiel",
  "Score-and-Reset Game": "Punkte-Runden",
  "Secret Unit Deployment": "Geheime Einheitenplatzierung",
  "Semi-Cooperative Game": "Semi-kooperatives Spiel",
  "Set Collection": "Sets sammeln",
  Simulation: "Simulation",
  "Simultaneous Action Selection": "Gleichzeitige Aktionswahl",
  "Slide / Push": "Schieben / Drücken",
  "Solo / Solitaire Game": "Solo / Solitär",
  "Square Grid": "Quadratraster",
  "Stat Check Resolution": "Attributprüfung",
  "Stock Holding": "Aktienbesitz",
  Storytelling: "Geschichtenerzählen",
  "Sudden Death Ending": "Sudden-Death-Ende",
  Tags: "Tags",
  "Take That": "Take That",
  "Team-Based Game": "Teams",
  "Tech Trees / Tech Tracks": "Technologiebäume / -pfade",
  "Tile Placement": "Legespiel",
  "Track Movement": "Streckenbewegung",
  Trading: "Tauschhandel",
  "Traitor Game": "Verräterspiel",
  "Tug of War": "Tauziehen",
  "Turn Order: Auction": "Zugreihenfolge: Auktion",
  "Turn Order: Claim Action": "Zugreihenfolge: Aktion wählen",
  "Turn Order: Progressive": "Zugreihenfolge: Progressiv",
  "Turn Order: Stat-Based": "Zugreihenfolge: Attributbasiert",
  "Variable Phase Order": "Variable Phasenreihenfolge",
  "Variable Player Powers": "Variable Spielerfähigkeiten",
  "Variable Set-up": "Variabler Aufbau",
  "Victory Points as a Resource": "Siegpunkte als Ressource",
  Voting: "Abstimmung",
  "Worker Placement": "Arbeiterplatzierung",
  "Worker Placement with Dice Workers":
    "Arbeiterplatzierung mit Würfelarbeitern",
  "Worker Placement, Different Worker Types":
    "Arbeiterplatzierung, verschiedene Arbeitertypen",
  "Zone of Control": "Kontrollzone",
};

/** BGG category/mechanic labels (EN) → German for categoriesDe/mechanicsDe. */
export function translateTaxonomy(en: string[]): string[] {
  return en.map((label) => BGG_TAXONOMY_DE[label] ?? label);
}
